apiVersion: "ploto.io/v1"
kind: DynamicExecutorPool
metadata:
  name: dep-crash-test
  namespace: ploto-demo
spec:
  initialExecutor: 2
  maxExecutor: 5
  minExecutor: 2
  webhook:
    service:
      namespace: ploto-system
      name: autoscaler-webhook-service
      path: /scale
      port: 8000
  container:
    command:
      - /app/bin/crash-demo
    args:
      - "--simulate-exe-time=60"
    env:
      - name: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    image: ccr.ccs.tencentyun.com/ploto/crash-demo:v1.5.3
    imagePullPolicy: Always
    name: crash-demo
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    securityContext:
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    workingDir: /
